runtime: python39

entrypoint: python web_ui.py

# Automatic scaling configuration
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.60
  max_instances: 5

env_variables:
  GOOGLE_CREDENTIALS: "<Paste your JSON content here>"
  DATABASE_EXCEL_PATH: "/app/SCADA TestData.xlsx"
  OPENAI_API_KEY: "<Your OpenAI API Key>"
  ROBOTNAME: "Royal"

# Optional: Static file handling (CSS, images, etc.)
handlers:
- url: /static
  static_dir: static

# Logs to be captured
beta_settings:
  cloud_logging: true
