runtime: python39  # Specifies the Python runtime version

entrypoint: gunicorn -b :$PORT web_ui:app  # Flask app entry point (update if necessary)

env_variables:  # Define environment variables required for your app
  DATABASEEXCEL_PATH: ${DATABASEEXCEL_PATH}  # Path to the database file
  GCLOUD_DEPLOY_SERVICE_KEY: ${GCLOUD_DEPLOY_SERVICE_KEY}  # GCloud deployment key
  GCLOUD_PROJECT: ${GCLOUD_PROJECT}  # GCloud project ID
  GOOGLE_CREDENTIALS: ${GOOGLE_CREDENTIALS}  # JSON content for Google services
  OPENAI_KEY: ${OPENAI_KEY}  # OpenAI API key
  ROBOTNAME: ${ROBOTNAME}  # Your robot's name

automatic_scaling:  # Automatic scaling configuration
  target_cpu_utilization: 0.65  # Target CPU utilization for scaling
  max_instances: 5  # Maximum number of instances
  min_instances: 1  # Minimum number of instances

handlers:  # URL routing
  - url: /static  # Serve static files
    static_dir: static

  - url: /.*
    script: auto  # Automatically map all requests to the app

instance_class: F2  # Defines the instance class (adjust based on your app's needs)

health_check:  # Health check configuration for the app
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
