services:
  - type: web
    name: voicechatbot
    env: python
    buildCommand: |
      apt-get update && apt-get install -y portaudio19-dev libasound2-dev python3-dev gcc && \
      pip install pipwin && \
      pipwin install pyaudio && \
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn web_ui:app --timeout 120 --workers 1 --threads 4 --worker-class gthread
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_CREDENTIALS
        sync: false
      - key: DATABASE_EXCEL_PATH
        value: /opt/render/project/src/SCADA TestData.xlsx
      - key: ROBOTNAME
        value: Royal
    healthCheckPath: /
