name: Deploy Voice Chatbot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Set Up Google Cloud Credentials
      run: |
        echo "${{ secrets.GoogleSST_Key_path }}" > google-key.json
        export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/google-key.json

    - name: Run the Application
      run: python web_ui.py
      env:
        OpenAI_key: ${{ secrets.OpenAI_key }}
        DatabaseExcel_path: ${{ secrets.DatabaseExcel_path }}
        RobotName: ${{ secrets.RobotName }}
