name: Deploy to Google App Engine

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main  # Deploy only on the main branch v2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Authenticate with Google Cloud
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCLOUD_PROJECT }}
        service_account_key: ${{ secrets.GCLOUD_DEPLOY_SERVICE_KEY }}

    # Step 3: Deploy the application
    - name: Deploy to App Engine
      run: |
        gcloud app deploy app.yaml --quiet
